apiVersion: v1
kind: Secret
metadata:
  name: taskmaster-secret
  namespace: taskmaster
type: Opaque
data:
  POSTGRES_USER: dGFza3VzZXI=        # base64("taskuser")
  POSTGRES_PASSWORD: dGFza3Bhc3M=    # base64("taskpass")

